### ISSUE TITLE
Cloud Run Worker

### ISSUE THREAD

**Issue by brianschardt** [anchan828/nest-bull#584]
Hey looking through your repos you have created some amazing packages. I noticed you are also very familiar with cloud run.
I want to get a bull bullmq working on cloud run. I am using your package: nest-bullmq 

I have tried and see that my service is connected to redis, but when an item is added to the queue my service does not pick it up on cloud run. I am wondering if you have any insight?

Thanks!

**Comment by anchan828** [comment]
Hi! thanks for your comment.
Did you look https://github.com/anchan828/nest-cloud-run-pubsub ?
I have already migrated from bullmq to nest-cloud-run-pubsub in my main project.

I think bullmq can’t use on Cloud Run because it doesn’t support minimum one instance.
However I think... you need to use Cloud Schedule and send http request to instance regularly. Then instance always runs.
Maybe bullmq will run.

**Comment by brianschardt** [comment]
Ok ill try that out. My thoughts for using redis instead of gcp pub sub is for the ease of developing locally. How hard is it to develop locally (not connected to the internet) using pub sub?

**Comment by anchan828** [comment]
Can you use docker? If so, it’s easy. You can use messagebird/gcloud-pubsub-emulator image.
And please check demo project https://github.com/anchan828/nest-cloud-run-pubsub-demo#readme

**Comment by brianschardt** [comment]
yep i use docker right now. Cool that looks awesome,is there by any chance a good visual ui package for pubsub?
Also, does it handle retries as well as bullmq?

**Comment by anchan828** [comment]
I am not sure that is there UI for pub/sub emulator. nest-cloud-run-pubsub-demo uses [@google-cloud/pubsub](https://www.npmjs.com/package/@google-cloud/pubsub) package. It is support to handle retries.

And I implemented retry feature in worker apart from @google-cloud/pubsub.
https://github.com/anchan828/nest-cloud-run-pubsub/blob/master/packages/worker/src/interfaces.ts#L25
