### ISSUE TITLE
forRootAsync commented out?

### ISSUE THREAD

**Issue by ejhayes** [anchan828/nest-bull#59]
I notice that the `forRootAsync` is currently commented out. Were there problems with this?

Referring to: https://github.com/anchan828/nest-bull/blob/master/packages/bull/src/bull.module.ts#L15

**Comment by anchan828** [comment]
Hi,

I have no idea how to inject for async providers...
https://github.com/anchan828/nest-bull/blob/support-async-for-root/packages/bull/src/bull-core.module.ts#L41-L50

I will add BullService provider that it can get queue instead of @Inject.
https://github.com/anchan828/nest-bull/blob/support-async-for-root/packages/bull/src/examples/8.async-basic.example.spec.ts#L18-L29

**Comment by anchan828** [comment]
Maybe I should add forFeature  for async like a TypeOrmModule.forFeature
https://docs.nestjs.com/techniques/database

**Comment by anchan828** [comment]
Released v0.3.7
we can get queues by BullService
https://github.com/anchan828/nest-bull/tree/master/packages/bull#getting-queue-using-bullservice

**Comment by ejhayes** [comment]
Wow @anchan828 you work quick!  I like the idea of something like `BullModule.forQueue(QUEUE_NAME)`

**Comment by anchan828** [comment]
Nice function name 👍
I created issue #72 for adding forQueue function. So this issue will close.

Thanks
